import MenuBar from '../../components/menuBar/MenuBar'
import './globals.css'
import { Inter } from 'next/font/google'

export const metadata = {
  title: 'THR',
  description: 'Generated by create next app',
}
const inter = Inter({ subsets: ['latin'] })

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className={inter.className} lang="en">

      <body >
        <MenuBar />
        <div className={"body"} >
          {children}
        </div>
      </body>
    </html>
  )
}
